### ISSUE TITLE
App selecionado e cópia do Termo de Uso

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-ConecteSUS#5]
# Documento: App e Termo de Uso
# Descrição
Essa issue tem como objetivo a criação de um documento que apresente o app escolhido e descreva os motivos e os critérios que foram utilizados nessa escolha. Deve ser incluído também no repositório uma cópia do termo de uso do aplicativo escolhido.

# Tarefas
- [x] Criar um documento com a descriçao do app escolhido e os critérios de escolha
- [x] Dar upload na cópia dos Termos de Uso do app
- [x] Atualizar o histórico de versões

# Lembre-se de checar se o github pages possui:
- [x] O histórico de versão padronizado.
- [x] O(s) autor(es) e o(s) revisor(es) para cada artefato.
- [x] A motivação e os critérios para a escolha do App.
- [x] Referências bibliográficas e/ou bibliografia em todos os artefatos.
- [x] As tabelas e imagens  (se houver) possuem legenda e fonte e  se elas são chamadas dentro dos texto.
- [x] Um texto fazendo uma introdução dos artefatos, por exemplo das “Ferramentas”.
- [x] Cópia do Termo de Uso, Direito de Uso ou Propriedade Intelectual do aplicativo permitindo o estudo na disciplina.

**Comment by GZaranza** [comment]
Foi criado o arquivo [app-selecionado.md](https://github.com/Requisitos-de-Software/2023.2-ConecteSUS/blob/main/docs/planejamento%20do%20projeto/app-selecionado.md) que fala sobre a escolha do app para o projeto

**Comment by izabellaalves** [comment]
Revisado!
