### ISSUE TITLE
Lista de apps avaliados

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-ConecteSUS#8]
# Documento: Lista de apps avaliados
# Descrição
Essa issue tem como objetivo registrar as avaliações individuais que os integrantes da equipe fizeram ao sugerir um aplicativo para o projeto da disciplina Requisitos de Software.

# Tarefas
- [x] Acessar o documento "lista-apps-avaliados.md", que se encontra na pasta "planejamento do projeto", dentro da pasta "doc"
- [x] Adicionar o app avaliado por você, com descrição e motivação da escolha.
- [x] Atualizar histórico de versões

# Observação
Todos são responsáveis por essa issue, então é necessário deixar um comentário quando terminar de cumpri-la. 
Assim que todos terminarem, a issue será fechada.

# Lembre-se de checar se o github pages possui:
- [x] O histórico de versão padronizado.
- [x] O(s) autor(es) e o(s) revisor(es) para cada artefato.
- [x] A motivação e os critérios para a escolha do App.
- [x] Referências bibliográficas e/ou bibliografia em todos os artefatos.
- [x] As tabelas e imagens  (se houver) possuem legenda e fonte e elas chamadas dentro dos texto.
- [x] Um texto fazendo uma introdução dos artefatos, por exemplo das “Ferramentas”.

**Comment by izabellaalves** [comment]
Feito. App Viva Bem adicionado na lista de apps avaliados.

**Comment by GZaranza** [comment]
Feito, fiz a análise do app ConecteSUS e já adicionei na lista de apps avaliados

**Comment by gabrielrosa09** [comment]
Análise do app calibre - E-book management realizada e adicionado na lista de apps avaliados.

**Comment by Lucas13032003** [comment]
Finalizado - app CNH Digital

**Comment by ZenildaVieira** [comment]
Feito. Análise do aplicativo e-Titulo incluido no documento.
